import pandas as pd

def load_ko00001(KEGG_DIR: str = ...): ...
def load_ko00002(KEGG_DIR: str = ...): ...
def load_entry(KEGG_DIR: str = ...): ...
def get_gmodule(genomeko: pd.DataFrame, KEGG_DIR: str = ...): ...
def demo2() -> None: ...
