def hsl2rgb(inputColor): ...
def hue2rgb_matrix(v1, v2, vH): ...
def hsl2rgb_matrix(colors): ...
def rgb2hsl(inputColor): ...
def rgb2hsl_matrix(colors): ...
def rbg_reverse_array(array): ...
def img_color(img_name) -> None: ...
