from typing import Any

def open_r(filename: str, *nargs, **vargs): ...
def write_file(file_name: str, content) -> None: ...
def write_json_file(file_name: str, obj: Any, indent: int = ...) -> None: ...
def read_json_file(file_name: str) -> Any: ...
def is_exist(file_name: str) -> None: ...
def eopen(file_name: str, *args, **kwargs): ...
