import abc
import argparse
from _typeshed import Incomplete as Incomplete

class ScriptBase(metaclass=abc.ABCMeta):
    def description(self) -> None: ...
    def define_parameters(self, *args, **kwargs) -> None: ...
    def modify_args(self, args) -> None: ...
    @abc.abstractmethod
    def run(self, args: argparse.Namespace) -> None: ...
    def define_option(self, *args, **kwargs) -> None: ...
    def define_parameter_bool(self, *args, **kwargs) -> None: ...
    def help(self) -> None: ...
    parser: Incomplete
    def parse_args(self) -> argparse.Namespace: ...
    def cli(self) -> None: ...

class TestScript(ScriptBase):
    def define_parameters(self) -> None: ...
    def run(self, args) -> None: ...
