from PyLib.PyLibTool.file_info import basicConfig as basicConfig
from PyLib.tool.timer import TimeCode as TimeCode, Timer as Timer

def test_Timer() -> None: ...
def test_format_time() -> None: ...
def test_TimeCode() -> None: ...
