import numpy
from typing import Tuple

def report_gap(seqtable: numpy.ndarray): ...
def delete_gap(seqtable: numpy.ndarray, DEGAP_THRESHOLD: float) -> numpy.ndarray: ...
def clean_seq(sequence: list): ...
def FORMAT(IOtext, *args: Tuple['namelist', 'seqarray', 'MAX_SEQUENCE_LEN']) -> dict: ...
def CLUSTAL(IOtext, *args: Tuple['namelist', 'seqarray', 'MAX_SEQUENCE_LEN']) -> dict: ...
def FASTA(IOtext, *args: Tuple['namelist', 'seqarray', 'MAX_SEQUENCE_LEN']) -> dict: ...
def format_input(format_func, path): ...
def format_output(format_func, path, DEGAP_THRESHOLD, namelist, seqarray, MAX_SEQUENCE_LEN, *args) -> None: ...

DEGAP_THRESHOLD: float
MAX_SEQUENCE_LEN: int
