from _typeshed import Incomplete
from typing import Dict

logger: Incomplete

def KMER_TABLE_FORMAT(kmer): ...
def set_backgroud_frequency(filepath: str): ...
def expected_frequency(sequence: str, base_backgroud_frequency: Dict[str, float]): ...
def most_n_kmers(kmer, kmer_len, base_backgroud_frequency): ...
def main() -> None: ...
