from PyLib.PyLibTool.file_info import verbose_import as verbose_import
from _typeshed import Incomplete
from pathlib import Path
from typing import Final, Generator, List, Literal, TextIO, Tuple

logger: Incomplete
main_lvls: Final[Incomplete]
levels: Final[List[Literal['k', 'p', 'c', 'o', 'f', 'g', 's']]]

def process_kraken_report_line(curr_str: str): ...
def kraken_iter(in_file: TextIO, include_x: bool = ...) -> Generator[Tuple[str, int], None, None]: ...
def format_taxon(taxon: str, formatleveli: int = ...): ...
def kraken_level_filter(in_file: TextIO, level: Literal['k', 'p', 'c', 'o', 'f', 'g', 's'], prokaryotes_only: bool = ...): ...
def kraken_summary(outdir: Path, *files): ...
