from _typeshed import Incomplete

def windowBam(bam, output, windowlength) -> None: ...

class window:
    contig: Incomplete
    start: Incomplete
    end: Incomplete
    mapq0: int
    totReadCount: int
    def __init__(self, contig, start, end) -> None: ...
    def recordCount(self, mapq0, totReads) -> None: ...
    def getRatio(self): ...
    def hasMapq0(self): ...
    def getBed(self): ...

def arg_parse(bam, output, windowlength): ...
def run() -> None: ...
