from PyLib.tool.wildcards import epder as epder, fmter as fmter, glob_path as glob_path, strip_constraints as strip_constraints
from _typeshed import Incomplete

test_patterns: Incomplete
files: Incomplete

def test_glob_path() -> None: ...
def test_fmter() -> None: ...
def test_fmter_fail_on_pattern() -> None: ...
def test_expder() -> None: ...
