from _typeshed import Incomplete

test_patterns: Incomplete

def test_create_pattern_blank() -> None: ...
def test_create_pattern_number() -> None: ...
def test_get_wildcard_names() -> None: ...
def test_get_wildcards_complex() -> None: ...
def test_get_wildcard_constraints() -> None: ...
def test_strip_wildcard_constraints() -> None: ...
def test_constraint_replace() -> None: ...
def test_regex() -> None: ...

files: Incomplete

def test_glob_wildcards() -> None: ...
