a: str
b: str

def test_formatter_args() -> None: ...
def test_formatter_kwargs() -> None: ...
def test_formatter_stepout() -> None: ...
def test_formatter_missing() -> None: ...
def test_formatter_quoter() -> None: ...
def test_expand() -> None: ...
def test_expand_args() -> None: ...
def test_formatter_kwargs_complex() -> None: ...
def test_apply_wildcards() -> None: ...
