from PyLib.biotool.kraken import kraken_level_filter as kraken_level_filter
from typing import Iterable, List, Optional, Set, TextIO, Tuple, Union

def read_table(text: Union[List[str], str, TextIO], sep: str = ..., annot: str = ..., title: Optional[List[str]] = ..., openit: bool = ...): ...
def DASTool_summary_iter(text: TextIO) -> Iterable[List[str]]: ...
def DASTool_scaffolds2bin_iter(text: TextIO) -> Iterable[Tuple[str, Set[str]]]: ...
def checkm_iter(text: TextIO) -> Iterable[Tuple[str, List[str]]]: ...
def gtdbtk_1_0_2_iter(text: TextIO): ...
def gtdbtk_1_5_1_iter(text: TextIO): ...
gtdbtk_iter = gtdbtk_1_5_1_iter

def featureCounts_iter(text: TextIO, ititle: Optional[List] = ...): ...
def emapper_g5f52332_iter(text: TextIO): ...
def emapper_ee27b8e_iter(text: TextIO): ...
emapper_iter = emapper_ee27b8e_iter
kraken_iter = kraken_level_filter
