from typing import TextIO, Tuple, Union

SUFFIX: str

def wrapStrFile(sth: Union[TextIO, str], **kwargs) -> TextIO: ...
def add_pubmed_item(item: dict, k0: str, v: str): ...
def pmiditer(text: Union[TextIO, str] = ...): ...
def report(file, *keys: Union[str, Tuple[str, str]]): ...
