# -*- coding: utf-8 -*-
"""
 * @Date: 2020-10-24 10:24:10
 * @LastEditors: Hwrn
 * @LastEditTime: 2020-10-24 10:38:46
 * @FilePath: /HScripts/Python/seqPipe/01_length_cut.py
 * @Description:
"""

from sys import argv, stderr
from Bio import SeqIO


__doc__ = """
    01_length_cut.py <in_file.fa> <out_file.fa> <threshold>
        @description:   Remove sequence shorter than given threshold.
                        This file is designed to control quality of
                        scaffolds.fa generated by assembly program like
                        megahit, spades, or idba.


        @param:         <in_file.fa>:   input file in FASTA format
                        <out_file.fa>:  output file
                        <threshold>:    threshold, typtically, 500
"""

if "-h" in argv or "--help" in argv:
    print(__doc__, file=stderr)
    exit(0)

sc, in_file, out_file, number = argv
num = int(number)
fout = open(out_file, 'w')
for line in SeqIO.parse(in_file, 'fasta'):
    if len(line.seq) >= num:
        fout.write('>'+str(line.id)+'\n'+str(line.seq)+'\n')
