from typing import Iterable, Mapping

def dissoc(mapping: Mapping, keys: Iterable) -> dict: ...
def dissoc_strict(mapping: Mapping, keys: Iterable) -> dict: ...
def select_keys(mapping: Mapping, keys: Iterable) -> dict: ...
