from _typeshed import Incomplete

class Tee:
    log: Incomplete
    logger: Incomplete
    def __init__(self, *args, filename: str = ..., **kwargs) -> None: ...
    def write(self, message) -> None: ...
    def flush(self) -> None: ...

class Redirector:
    stdout: Incomplete
    stderr: Incomplete
    mode: str
    def __init__(self, stderr=..., stdout=...) -> None: ...
    old_stderr: Incomplete
    old_stdout: Incomplete
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
