from _typeshed import Incomplete
from collections.abc import Generator
from typing import List

def appendcwd() -> None: ...
def TemporaryDirectory(**kwargs) -> Generator[Incomplete, None, None]: ...
def makedirs(path: str, *paths: str) -> str: ...
def verify_file_exists(file_path: str, message: str = ...) -> None: ...
def verify_dir_exists(dir_path: str, message: str = ...) -> None: ...
def list_dir(dir: str, filter) -> List: ...
def fine_all_files(dir: str, filter) -> List: ...
def abs_user_path(dir: str) -> str: ...

class Path:
    def __init__(self, source_path, desc) -> None: ...
    @classmethod
    def cd(cls, *source_path, desc: str = ...): ...
    @classmethod
    @property
    def root_path(cls): ...
    @property
    def source_path(self): ...
    @property
    def desc(self): ...
