from typing import Dict, Sequence, Tuple, Union

def split_kw_args(sh_kwargs: str): ...
def printsh(value, flow: int = ..., end: str = ...) -> None: ...
def runsh(tokens: Sequence[str], env: Dict[str, str] = ..., trim: bool = ..., check_call: bool = ...) -> Tuple[str, str]: ...
def runsh_safe(tokens: Union[str, list], env: Dict[str, str] = ..., trim: bool = ..., check_call: bool = ...) -> Tuple[str, str]: ...
