def test_download_refseq() -> None: ...
def test_download_wgs() -> None: ...
def test_download_genebank() -> None: ...
def test_retries_download() -> None: ...
def test_retries_download_fail() -> None: ...
