import logging
from pathlib import Path
from typing import Dict, Optional

def extract_doc(module_doc: Optional[str] = ...) -> Dict: ...
def verbose_import(module_name, module_doc: Optional[str] = ...) -> logging.Logger: ...
def basicConfig(logger_level: Optional[str] = ..., _logger_level=...): ...
def md5sum(text: Optional[bytes] = ..., file: Optional[Path] = ..., c: Optional[str] = ...): ...
