import argparse
from _typeshed import Incomplete as Incomplete
from typing import TextIO, Tuple

logger: Incomplete

def rename_cut(fi: TextIO, fo: TextIO, threshold: int = ..., name: str = ...): ...
def main(fi: TextIO, fo: TextIO, threshold, name): ...
def get_args() -> Tuple: ...
def set_args(parser: argparse.ArgumentParser): ...
def run() -> None: ...
