from typing import Callable, Dict, List, TextIO, Union

line: str

def sickle_mapper(text: TextIO): ...
def bbmap_mapper(text: TextIO, lastline: str = ...): ...
def assem_mapper(text: TextIO): ...
def collect_folder(path: str, mapper: Callable[[TextIO], List[str]], suffix: str = ...): ...
def print_table(header: Union[List, Dict], results: Union[List, Dict] = ..., output: TextIO = ..., sep: str = ...): ...
def test() -> None: ...
