from Bio import SeqRecord as SeqRecord
from _typeshed import Incomplete as Incomplete
from typing import Iterable, Optional, Set

class PrefixFiles:
    prefix: Incomplete
    def __init__(self, prefix) -> None: ...
    def __call__(self, suffix: str, check_exist: bool = ...) -> str: ...

def fa_filt_iter(fas: Iterable[SeqRecord.SeqRecord], keepIds: Set[str], threshold: Optional[int] = ...): ...
def gff_filt_iter(gffin: Iterable[str], keepIds: Set[str]): ...
def parse_args() -> None: ...
def main(in_file_prefix, num, out) -> None: ...
