from _typeshed import Incomplete as Incomplete
from typing import Dict, List, TextIO, Tuple

logger: Incomplete

def MAG_seq_features(bin_filename: str, ctg_depth: Dict[str, Tuple[Tuple[int, float], List[float], List[float]]]): ...
def wrap_depth(fi: TextIO): ...
def merge_checkm_bin(binner_basedir: str, metawrap: bool = ..., depth_file: str = ..., summary_dict: Dict[str, List[str]] = ...): ...
def merge_checkm_taxon(binner_basedir: str, file_taxon: str, summary_dict: Dict[str, List[str]] = ...): ...
