def hsl2rgb(inputColor) -> None: ...
def hue2rgb_matrix(v1, v2, vH) -> None: ...
def hsl2rgb_matrix(colors) -> None: ...
def rgb2hsl(inputColor) -> None: ...
def rgb2hsl_matrix(colors) -> None: ...
def rbg_reverse_array(array) -> None: ...
def img_color(img_name) -> None: ...
