from PyLib.PyLibTool.file_info import basicConfig as basicConfig, extract_doc as extract_doc, md5sum as md5sum, verbose_import as verbose_import
from PyLib.test import test_file_path as test_file_path

def test_extract_doc() -> None: ...
def test_verbose_import() -> None: ...
def test_basicConfig() -> None: ...
def test_md5sum() -> None: ...
