import argparse
from _typeshed import Incomplete
from typing import Tuple

logger: Incomplete

def main(): ...
def get_args() -> Tuple: ...
def set_args(parser: argparse.ArgumentParser): ...
def run() -> None: ...
