# -*- coding: utf-8 -*-
"""
 * @Date: 2021-03-15 11:07:29
 * @LastEditors: Hwrn
 * @LastEditTime: 2022-01-21 14:53:58
 * @FilePath: /metaSC/PyLib/PyLibTool/file_info.py
 * @Description:
    Extract information in __doc__
"""

import logging


def extract_doc(module_doc: str) -> dict:
    """
    Extract header generated by 'korofildheader'

    >>> import PyLib.PyLibTool.file_info
    >>> from PyLib.PyLibTool.file_info import extract_doc
    >>> extract_doc(PyLib.PyLibTool.file_info.__doc__)["FilePath"]
    ' /metaSC/PyLib/PyLibTool/file_info.py'
    >>> extract_doc(PyLib.PyLibTool.file_info.__doc__)["Description"]
    '\n    Extract information in __doc__'
    """
    doc_list = module_doc.split(' * @')
    doc_dict = {}
    k = 'description'
    for item in doc_list:
        item = item.strip().split(':', 1)
        if item == ['']:
            continue
        elif len(item) == 1:
            doc_dict[k] += ' * @ ' + item[0]  # undefined action
        elif len(item) == 2:
            k, v = item
            doc_dict[k] = v

    return doc_dict


def verbose_import(module_name, module_doc) -> logging.Logger:
    """
    """
    doc_dict = extract_doc(module_doc)
    logger = logging.getLogger(module_name)
    LastEditTime = doc_dict["LastEditTime"]
    logger.debug(f'import version {LastEditTime} -- {module_name}')
    return logger


verbose_import(__name__, __doc__)
