# -*- coding: utf-8 -*-
"""
 * @Date: 2021-03-15 11:07:29
 * @LastEditors: Hwrn
 * @LastEditTime: 2021-06-01 14:28:21
 * @FilePath: /metaSC/PyLib/PyLibTool/file_info.py
 * @Description:
"""
import logging


def extract_doc(module_doc: str) -> dict:
    """ Extract header generated by 'korofildheader'
    """
    doc_list = module_doc.split(' * @')
    doc_dict = {}
    k = 'description'
    for item in doc_list:
        item = item.strip().split(':', 1)
        if item == ['']:
            continue
        elif len(item) == 1:
            doc_dict[k] += ' * @ ' + item[0]  # undefined action
        elif len(item) == 2:
            k, v = item
            doc_dict[k] = v

    return doc_dict


def verbose_import(module_name, module_doc):
    doc_dict = extract_doc(module_doc)
    logger = logging.getLogger(module_name)
    LastEditTime = doc_dict["LastEditTime"]
    logger.debug(f'import version {LastEditTime} -- {module_name}')


verbose_import(__name__, __doc__)
