from PyLib.biotool import ec as ec
from PyLib.test import test_file_path as test_file_path

def test_check_title() -> None: ...
def test_check_entry_complete() -> None: ...
def test_parse_entry() -> None: ...
def test_ec_entry() -> None: ...
def test_ec_entry_str() -> None: ...
def test_ec_entry_str_renamed() -> None: ...
def test_parse_id() -> None: ...
def test_bind_text() -> None: ...
def test_parse_de() -> None: ...
def test_parse_an() -> None: ...
def test_parse_ca() -> None: ...
def test_parse_cc() -> None: ...
def test_parse_dr() -> None: ...
def test_extract_transferred_entries() -> None: ...
def test_ecdb() -> None: ...
