from typing import Literal

def report_kraken_level(level: Literal['k', 'p', 'c', 'o', 'f', 'g', 's'], kraken_reports, threads: int = ...): ...
def easy_click(ctx, loglevel: str, output_prefix: str, kraken_report_pattern: str): ...
def bar(ctx, taxon, threads) -> None: ...
def rare(ctx, step, repeat, threads) -> None: ...
