from _typeshed import Incomplete as Incomplete
from pathlib import Path

logger: Incomplete

def remove_suffix(name: str, suffix: str = ...): ...
def diamond_check_db(fastapath: Path, outdir: Path, threads: int = ...): ...
def diamond_blastp(query: Path, db: Path, level: str = ..., outdir: Path = ..., threads: int = ...): ...
def diamond_1to1(genome1: Path, genome2: Path, out: Path, sensitive_level: str = ..., threads: int = ...): ...
def check_diamond_out(diamond_out, head_n: int = ..., keep_columns: list = ...): ...
