from typing import Dict, Iterable, List, Tuple

def seq_GC_len(seqs: Iterable[Tuple[str, str]]) -> Dict[str, Tuple[int, int, int]]: ...
def length_NL(seqs: Iterable[Tuple[str, str]], pcg: float = ...) -> Tuple[int, int]: ...
def statistic_fna(seqs: Iterable[Tuple[str, str]]) -> Tuple: ...
def seq_total_depth(ctg_depth: dict, seqs: Iterable[Tuple[str, str]]) -> Tuple[float, List[float]]: ...
