import pandas as pd
from _typeshed import Incomplete as Incomplete
from pathlib import Path
from typing import Generator, Literal, NamedTuple, Union, overload

ModelSEEDDatabase: Incomplete

def set_seed_db(ModelSEEDDatabase_: Path = ...): ...
def load_default_seed_db(ModelSEEDDatabase_: Path = ...): ...

class Reaction(NamedTuple):
    id: str
    ins: list[str]
    outs: list[str]
    direction: Literal['=', '>', '<', '?']
    def __hash__(self) -> int: ...
    @staticmethod
    def cleancompound(raw: str): ...
    @classmethod
    def cleanequation(cls, id: str, raw: str, direction: Literal['=', '>', '<', '?']): ...

def load_clean_SEED_reactions(ModelSEEDDatabase) -> None: ...
def load_KO_modelseed_translations(ModelSEEDDatabase) -> None: ...
@overload
def genome_ko2rxn(kos: Generator[str, None, None], *, ko_modelseed_translations: dict[str, list[str]], clean_reactions: dict[str, Reaction]) -> pd.Series: ...
@overload
def genome_ko2rxn(kos: Generator[str, None, None], *, ModelSEEDDatabase: Path) -> pd.Series: ...
def genome_rxn2cpd(genome_rxn: Union[pd.Series, dict[str, list[Reaction]]]): ...
def genome_rxn2mo(grxn) -> None: ...
