def list_MAGs(MAG_file_path: str, endswith: str = ...) -> list: ...
def collect_MAGs_msg(MAG_file_path: str, depth_file: str = ..., checkM_file: str = ..., iRep_file: str = ..., gtdbtk_path: str = ...): ...
