from _typeshed import Incomplete as Incomplete
from pathlib import Path

def assign_unipprt_fa_features(headline: str = ...): ...

class _UniProtTaxonomyDB:
    taxonomy_file: Incomplete
    version: Incomplete
    def __init__(self, taxonomy_file: Path) -> None: ...
    def load(self) -> None: ...

class UniProtTaxonomy:
    s: Incomplete
    taxon_id: Incomplete
    def __init__(self, taxon_id: int) -> None: ...
    def __new__(cls, taxon_id: int): ...
    def is_root(self) -> None: ...
    def get_parent(self, raw: bool = ...): ...
    parent: Incomplete
    @property
    def parents(self) -> None: ...
    @property
    def kids(self) -> None: ...
    @classmethod
    def init(cls, taxonomy_file: Path, name: Incomplete | None = ...): ...
    @classmethod
    def find(cls, somename, topn: int = ..., raw: bool = ...): ...
