from _typeshed import Incomplete as Incomplete

def windowBam(bam, output, windowlength) -> None: ...

class window:
    contig: Incomplete
    start: Incomplete
    end: Incomplete
    mapq0: int
    totReadCount: int
    def __init__(self, contig, start, end) -> None: ...
    def recordCount(self, mapq0, totReads) -> None: ...
    def getRatio(self) -> None: ...
    def hasMapq0(self) -> None: ...
    def getBed(self) -> None: ...

def arg_parse(bam, output, windowlength) -> None: ...
def run() -> None: ...
