import argparse
from collections import OrderedDict

def str_to_bool(s: str) -> bool: ...
def define_parameters(parser: argparse.ArgumentParser) -> None: ...
def define_option(parser: argparse.ArgumentParser, name: str, default, help: str, short_name: str = ...) -> None: ...
def define_parameter_bool(parser: argparse.ArgumentParser, name: str, default, help: str) -> None: ...
def send_parser(description) -> None: ...
def markerGeneToContig(markerSet, resultsManager, reportContig: bool = ...): ...
def generateAdditionalCsv(out_file, markerSet, contigs, ms_wight) -> None: ...
def getBinsToModify(ckmap: OrderedDict, Compl_THRESHOLD: int = ..., Contai_THRESHOLD: int = ...): ...
def main() -> None: ...
