import pandas as pd
from .LinkDB import load_brite as load_brite, module_from_brite as module_from_brite

def load_ko00001(KEGG_DIR: str = ...): ...
def load_ko00002(KEGG_DIR: str = ...): ...
def load_entry(KEGG_DIR: str = ...): ...
def get_gmodule(genomeko: pd.DataFrame, KEGG_DIR: str = ...): ...
def demo2() -> None: ...
